---
version: '3.7'
services: 
  squashtm:
    image: exoplatform/squash-tm
    ports:
      # On expose le port 8080 du service squash auquel je pourrais accéder via localhost:8081
      - 8081:8080/tcp
    links:
      - postgre-squash
    environment:
      - USER=squash-tm
      - PASSWORD=initial_pw
      - DATABASE=squashtm

  postgre-squash:
    image: postgres:9.6
    volumes:
      - DB_backup:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=squash-tm
      - POSTGRES_PASSWORD=initial_pw
      - POSTGRES_DB=squashtm
volumes:
  DB_backup: